Dave/opportunity tracking backend integration
MarkCarsonDev/SqueakPeek pull request #125
Opened 2024-11-17 17:04 UTC by Serranoda

Added backend integration to the opportunity cards.

2024-11-17 22:25 UTC, MekhiHart requested changes

2024-11-17 22:25 UTC, MekhiHart commented on client/src/lib/utils/fetchOpportunityTracking.ts
Can this query be made when the opportunities are fetched? It seems necessary to fetch the aggregates for each opportunity individually

2024-11-17 22:25 UTC, MekhiHart commented on client/src/ui/explore/OpportunityList.tsx
> +      try {
try and catch is unnecessary since fetching with the supabase query doesn't throw an error. It just returns the error object

2024-11-17 22:25 UTC, MekhiHart commented on client/src/lib/utils/fetchOpportunityTracking.ts
If this the query is difficult to do in Supabase, you can opt to make a database function.

Here is the query that fetches the relevant metadata:
`
select *
from opportunity
inner join company_thread on company_thread.opportunity_id = opportunity.opportunity_id
inner join opportunity_tracking on opportunity_tracking.opportunity_id = opportunity.opportunity_id
`

- See the `insert_private_conversation` as reference to creating the db function in supabase.
- See the `insertPrivateConversation` util function to see how to invoke the db function in the client side

2024-11-18 05:39 UTC, MekhiHart requested changes

2024-11-18 05:39 UTC, MekhiHart commented on client/src/ui/explore/OpportunityCard.tsx
Total applied stats is incorrect for the job cards. Total applied should be the sum of all the aggregates not just 'applied'

<img width="891" alt="image" src="https://github.com/user-attachments/assets/84e44bd0-1734-499a-8a6e-c66308734eff">

2024-11-18 05:39 UTC, MekhiHart commented on client/src/ui/explore/OpportunityCard.tsx
Can we also remove the number of messages for each job card. I don't think it's too helpful for the user to see that

2024-11-18 05:39 UTC, MekhiHart commented on client/src/ui/explore/OpportunityCard.tsx
Couple of things:
- Can we make the bar be rounded? It might be tough to handle if some of the statuses are missing
- Can we also change the color to be consistent for each status in the tracking page? (See screenshot)
<img width="480" alt="image" src="https://github.com/user-attachments/assets/a564863a-b743-4ace-bf2a-b14410048f4b">

2024-11-18 05:39 UTC, MekhiHart commented on client/src/ui/explore/OpportunityCard.tsx
There should also be an 'initial screen' stage

2024-11-18 07:09 UTC, Serranoda commented on client/src/ui/explore/OpportunityCard.tsx
> There should also be an 'initial screen' stage

Isnt that what the applied column would be for? that for those who have applied but not yet moved to another stage

2024-11-18 16:26 UTC, MekhiHart commented on client/src/ui/explore/OpportunityCard.tsx
The applied is the sum of each aggregate. Whenever the user is any stage, they are considered applied

2024-11-18 16:54 UTC, MekhiHart approved these changes

2024-11-18 16:54 UTC, merged