Noah/refactor pageheaders
MarkCarsonDev/SqueakPeek pull request #171
Opened 2024-12-07 22:24 UTC by noahdaniels9

Custom hooks added for client-side pages. Home and About Us are server side so changing the metadata directly is valid.

2024-12-07 23:52 UTC, MekhiHart requested changes
Are custom page headers that beneficial to have? I don't see the benefits of turning server components into client component that impact performance outweighs custom metadata

2024-12-07 23:52 UTC, MekhiHart commented on client/src/app/(main)/message/private/[conversationId]/page.tsx
Let's not turn pages that are already server side into client side for the purpose adding page headers

2024-12-08 20:47 UTC, noahdaniels9 commented
re-opening PR after successful build

2024-12-09 00:06 UTC, MekhiHart approved these changes

2024-12-09 00:07 UTC, merged