Hao/job card component
MarkCarsonDev/SqueakPeek pull request #73
Opened 2024-10-26 02:04 UTC by haophn01

JobCard Component
- Keep in mind this component will be only available for page "track" only. 
- There was some minor change in term of styling and name between file "Track.ts", "StageColumn.tsx", "UpdateStatus.tsx" and "Page.tsx" in track folder. 
- There is no changing color when moving the card yet but it will implement after the job card. Since it involving with the styling issue. (As in a different PR).

2024-10-26 03:04 UTC, MekhiHart requested changes

2024-10-26 03:04 UTC, MekhiHart commented on client/src/ui/track/JobCard.tsx
Couple of things:

Card component
- Remove Box shadow on card
- Make action button icons bigger
- Avatar is flushed to the card is very tight around it. Add padding around the avatar to give it room 
- The column width is expanding in size when a new card is added. Can we make the columns a fixed size.
- Add more spacing around the Card component so it's not claustrophobic
- 

Update Status
- Can we make Interviewing say the entire word not just "IR"
- Can we add spacing in "OnlineAssessment" --> "Online Assessment"
- (nit): Change the order of the options from top to bottom: Applied, Rejected, Online Assessment, "Interviewing, Rejected". For UX purposes, an applicant is most likely going to get rejected to a application they apply. It's just easier for them to click on rejected option when it's nearer to the top rather than down

2024-10-26 05:49 UTC, haophn01 commented on client/src/app/(main)/track/page.tsx
> +  const stages:  Omit<StageColumnProps, 'setApplicationStatus'>[] = [
oppsie, I was testing something, it should not be there haha.

2024-10-26 05:50 UTC, haophn01 commented on client/src/ui/track/JobCard.tsx
all fixed!

2024-10-27 04:33 UTC, MekhiHart requested changes
- The moving of the card when it get's placed on the column should get fixed. But that fix can be placed on a different PR 
- Can we also make the page not scrollable vertically? I don't know why the bottom section needs to be there. No need for  scrollable when there's no content there
![Screenshot 2024-10-26 at 9 51 16 PM](https://github.com/user-attachments/assets/90d6acf7-72cd-4091-96e5-f8e1277698f3)


Otherwise, awesome job Howie!

2024-10-27 04:33 UTC, MekhiHart commented on client/src/ui/track/JobCard.tsx
> +              icon={faFacebookMessenger}
Can we change this to the conversation icon instead to make it consistent with the UI on the navbar

![image](https://github.com/user-attachments/assets/74a37ea3-5f6f-4131-a65d-4974b71e2890)

2024-10-27 06:05 UTC, MekhiHart approved these changes

2024-10-27 06:06 UTC, merged